# Site settings
title: okc Blog
SEOTitle: okc | Blog
header-img: img/bg (1).jpg     #首页头部背景图片
email: kevin_okc@qq.com
# description: "A dreamer, and a doer." 真正的description在index.html
keyword: ""
url: "https://okcokc.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/okcokc/okcokc.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "This is a description"
sidebar-avatar: /img/my_image.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings 页面底部社交平台帐号展示
RSS: false
#weibo_username:     okcokc
#zhihu_username:     okcokc
github_username:    okcokc
#facebook_username:  
jianshu_username:   a848505237cd
#twitter_username:   okcokc




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
#一页的文章数量
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: okcokc

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: ca3fc9736248f471699c                            #生成的clientID
  clientSecret: acf206709d5c52a08ff75866e45ee6d621b570be   #生成的clientSecret
  repo: okcokc.github.io    #仓库名称
  owner: okcokc    #github用户名
  admin: okcokc
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname'


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: d667955a219f62d97867655482f386c6

# Google Analytics
# Format: UA-xxxxxx-xx
ga_track_id: 'UA-137508302-1'            
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "myBlog",
        href: "https://okcokc.github.io"
    },{
        title: "my简书",
        href: "https://www.jianshu.com/u/a848505237cd"
    }
]
